dist: bionic
language: python

python:
  - "3.6"

notifications:
  email: false

git:
  submodules: false

branches:
  only:
  - master

addons:
  apt:
    packages:
      - clang
      - cmake
      - cmake-data
      - gcc
      - python-dev
      - libgmp10
      - libgmp-dev
      - libssl-dev
      - libffi-dev

before_install:
  - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
  - bash ./travis/build_relic.sh
  - pip3 install codecov coverage msgpack

install:
  - pip3 install -v -e '.[dev]'

script:
  - coverage run --source=petrelic -m pytest

after_success:
  - codecov
