dist: bionic
language: python

python:
  - "3.6"

notifications:
  email: false

git:
  submodules: false

branches:
  only:
  - master

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev libgmp10 libgmp-dev libssl-dev libffi-dev
  - bash ./travis/build_relic.sh
  - pip3 install -v -e '.[dev]'

script:
  - python3 -m pytest
