dist: bionic
language: python

python:
  - "3.6"

notifications:
  email: false

git:
  submodules: false

branches:
  only:
  - master

addons:
  apt:
    packages:
      - clang
      - cmake
      - cmake-data
      - gcc
      - python-dev
      - libgmp10
      - libgmp-dev
      - libssl-dev
      - libffi-dev

install:
  - bash ./travis/build_relic.sh
  - pip3 install -v -e '.[dev]'

script:
  - python3 -m pytest
